### PR TITLE
Improved render

### PR DESCRIPTION
**Pull request by Avenger-Bagnarol**
[super_render.zip](https://github.com/SoftSimu/CellSim3D/files/3148922/super_render.zip)

A improved version of render which colors differently cells with different stiffness and automatically moves the camera such that every cell is viewed. It doesn't need a .blend file, to run type:
blender -b -P scripts/super_render.py -- file.xys [-options]
It is zipped because of GitHub, I don't know if it automatically gets unzipped.

### CODE REVIEW

**Comment by pmadhikar** [comment]
You need to push your changes to GitHub and submit a pull request against
the master branch there. Maybe you can have a look at the GitHub tutorial?

**Comment by pmadhikar** [comment]
Please see the [Github Tutorial](url) and follow the procedure there.

**Comment by Avenger-Bagnarol** [comment]
I know the basics of Git, but I am not allowed to push changes from
terminal (of course). Moreover, the link you put is not working.
Please tell me more specifically what to do or, simply, push the file I
attached previously, super_render.py. I won't get offended :-)

Il giorno mer 8 mag 2019 alle ore 11:20 pmadhikar <notifications@github.com>
ha scritto:

**Comment by pmadhikar** [comment]
Ah, yes the link indeed doesn't work. My bad. 

There is a good chance that we'll need to make some changes to the script before it goes into the master branch. If I push changes, it is likely that the repository will break for you. It is normal to not have push access (even I am not allowed to push to master). 

Here is what you should do: 

1. Fork the Cellsim3D repo.
2. Set your fork as a remote in your repository. 
3. Push your changes to a new branch on your fork(don't push to master on your fork).
4. Submit pull request from your branch in your fork against the master branch in the main CellSim3D repo 
5. I may request changes, make them and push to your branch. The pull request will update itself. 
6. Once everything looks good, I'll merge it into master here. 
7. Update your fork (github will prompt you)
8. Pull into the local repo on your computer. 
9. Done. 
10. Delete your branch. 

This seems overly complicated, but trust me it's worth it. It also gets easier and easier every time you do it. Many more details are given at https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by pmadhikar** [comment]
By the way, I forgot. 

Don't create a new script. Add the features you want to render.py. It can be an optional argument.

**Comment by Avenger-Bagnarol** [comment]
I think I successfully created the right pull request. Please give me
feedback.
I am also asking a couple of new questions on the group.
Thanks again for your support!

Il giorno ven 10 mag 2019 alle ore 10:50 pmadhikar <notifications@github.com>
ha scritto:

**Pull request closed without merging**
